version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

    ports:
      - "5432:5432"
    networks:
    - backend

  shop:
    build:
      context: ./shop
      dockerfile: Dockerfile

    container_name: shop
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://admin:123@db:5432/postgres?sslmode=disable
    networks:
      - backend
    ports:
      - "8080:8080"

networks:
    backend:
      driver: bridge